# Generated by Django 3.1.7 on 2021-04-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('logo', models.ImageField(upload_to='pics')),
                ('name', models.CharField(max_length=100)),
                ('heading', models.CharField(max_length=100)),
            ],
        ),
    ]
