# Generated by Django 3.1.7 on 2021-04-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20210408_0808'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=300)),
            ],
        ),
    ]
